### ISSUE TITLE
Is the TT Premium Edition Case Fan Controller supported yet?

### ISSUE THREAD

**Issue by vimaxus** [fu-raz/FanControlThermaltake#1]
Sorry for writing in issues, couldn't find the discussions page.

Is the TT Premum Edition supported? I can't seem to find the "regular" fan controller in the photo and so far it seems the only way I could control fans with [fan controller](https://github.com/Rem0o/FanControl.Releases)

Thank you

**Comment by fu-raz** [comment]
I'm sorry for the late reply. I wasn't aware people were actually trying to use this plugin. It should detect the TT Premium Edition as this is the one I have. I just didn't know what to call it

**Comment by baylockzathras** [comment]
Hi, Apologies if covered elsewhere, however i cant seem to find it.
Plugin does not show on FC, am i missing something? i copied over the .dll or is there another step?

Thanks.

**Comment by fu-raz** [comment]
Hmmm, that's strange. Perhaps it's a different device than the one I'm using. Do you have a link with some more details on your device?

I wrote a small tool which tries to detect TT controllers and their product IDs. Could you check if yours is detected?
[TTTest.zip](https://github.com/fu-raz/FanControlThermaltake/files/10194828/TTTest.zip)

This is the compiled version of this: https://github.com/fu-raz/FanControlThermaltake/tree/main/ThermaltakeRiingPlusTest

**Comment by fu-raz** [comment]
This should be working in the latest version now! https://github.com/fu-raz/FanControlThermaltake/releases/tag/v0.0.3

**Comment by baylockzathras** [comment]
Apologies, must have missed the original reply, im not overly active on git until i need something.
Im a bit of a leach in that respect, ill test them out for you.

Edit:
This is what i got from the tool:
Found Thermaltake device with Vendor ID 9802 and Product ID 8101
We found an unsupported TT device with product ID 8101
We found 1 Thermaltake devices, 0 supported and 1 unsupported
Please raise an issue here with the unsupported product ID's: https://github.com/fu-raz/FanControlThermaltake/issues
Press any key to exit...

**Comment by fu-raz** [comment]
@baylockzathras Please try the v1.0.0 version. This should fix all problems and add support for all the devices!

**Comment by baylockzathras** [comment]
Hi, Will test it out, the controller came in this case, tho i cant seem to find anything on the actual controller.
https://www.thermaltake.com.au/view-71-tempered-glass-edition.html

**Comment by baylockzathras** [comment]
Apologies, my understanding of the process has been exceeded.

Am i to compile and test, or is there a dll i cant see?

Thankyou.

Edit:
Never mind, i figured out how to get the file.

**Comment by baylockzathras** [comment]
Seems to be working.
Detects as TT Ring Plus Controller.

Thankyou verry much.
