### ISSUE TITLE
Ability to set fans to 0%

### ISSUE THREAD

**Issue by k3mic** [fu-raz/FanControlThermaltake#11]
Looks like the min speed I can go is about 600-ish rpm which is around 30% in FanControl. Is that expected? (Swafan ex 12)

I have a de-shrouded GPU and would be interested in having the fans fully stop when the system is idle. Great plugin also. :)

**Comment by k3mic** [comment]
Oh... nvm. Looks like even with the TT default software, min speed is 30%. Bummer

**Comment by DrShnobs** [comment]
how did you install the plugin i have been having problems

**Comment by fu-raz** [comment]
Unfortunately we're bound by the limitations of the TT hardware. So I guess 30% is the minimum
