### ISSUE TITLE
Plugin Failing to load

### ISSUE THREAD

**Issue by mashmunONE** [fu-raz/FanControlThermaltake#2]
I've placed the plugin dll into the plugin folder.
After starting FanControl it states that "Failed to load the Plugin FanControl.thermaltakeRiingPlus.dll. Make sure the plugin's dll is unlocked in its Properties"

Any help would be appreciated on installing this.

**Comment by fu-raz** [comment]
Sorry for the late reply, I didn't know this was actually being used. Have you been able to get it running? Maybe it's a version problem. It has been a while since I tried it myself actually

**Comment by fu-raz** [comment]
I just had this error message myself. Windows 11 locks downloaded DLL files. You have to right click the DLL in file explorer, go to properties and disable the blockage of the DLL file.

I even had to go so far as to copy the FanControl folder and DLL somewhere to get it to load.
