### ISSUE TITLE
Only detecting 4/5 riing quad fans

### ISSUE THREAD

**Issue by PunchingJay** [fu-raz/FanControlThermaltake#3]
Hi, 
I just found your plugin and I am sooo happy I am able to control my Riing Quad fans in Fan control now! 
The only issue I am having is, I use 2x controllers, one with 5x fans and one with 4x, Fan control is only detecting 4 fans on each controller. So unfortunately one fan is not able to be controlled. 
![rcbsidd](https://user-images.githubusercontent.com/19505706/199139487-aa6d3dae-8c6d-4d25-9560-95c6bae84cd3.png)

**Comment by fu-raz** [comment]
It should detect the controller based on the RPM. I'll see if there's anything wrong

**Comment by fu-raz** [comment]
Ok so my for loop only does 4 out of 5 fans.. I'll see if I can change it and release an update haha

**Comment by fu-raz** [comment]
Could you try v0.0.2? https://github.com/fu-raz/FanControlThermaltake/releases/tag/v0.0.2

**Comment by PunchingJay** [comment]
It is indeed working now! Thank you so so much

**Comment by fu-raz** [comment]
You are very welcome!
