### ISSUE TITLE
Unsupported Product ID 8101

### ISSUE THREAD

**Issue by rdfriese** [fu-raz/FanControlThermaltake#4]
Opening an issue as suggested by your test app:

Found Thermaltake device with Vendor ID 9802 and Product ID 8101
We found an unsupported TT device with product ID 8101
We found 1 Thermaltake devices, 0 supported and 1 unsupported

Thanks for your work!

**Comment by fu-raz** [comment]
I found the API for your device here: https://github.com/MoshiMoshi0/ttrgbplusapi/blob/master/controllers/riing-plus.md
Doesn't look like much work to implement, aside from having to refactor some things to make the plugin more modular. Give me a few days!

Oh and Merry Christmas!

**Comment by rdfriese** [comment]
Awesome thank you! (and happy New Years!)

**Comment by Loki1147** [comment]
Hi i have thesame problem with the product id 8102.
 it is also an RGb fan controller.

**Comment by clutchthrower** [comment]
> Opening an issue as suggested by your test app:
> 
> Found Thermaltake device with Vendor ID 9802 and Product ID 8101 We found an unsupported TT device with product ID 8101 We found 1 Thermaltake devices, 0 supported and 1 unsupported
> 
> Thanks for your work!

Try this quick patch I made. I had the same VID:PID

https://github.com/clutchthrower/FanControlThermaltake/releases/tag/patch

**Comment by Loki1147** [comment]
> > Opening an issue as suggested by your test app:
> > Found Thermaltake device with Vendor ID 9802 and Product ID 8101 We found an unsupported TT device with product ID 8101 We found 1 Thermaltake devices, 0 supported and 1 unsupported
> > Thanks for your work!
> 
> Try this quick patch I made. I had the same VID:PID
> 
> https://github.com/clutchthrower/FanControlThermaltake/releases/tag/patch

Works for me Thanks :)

**Comment by fu-raz** [comment]
Sorry it took so long, I've added this functionality to the latest version: https://github.com/fu-raz/FanControlThermaltake/releases/tag/v0.0.3

It should now be easier to add more controllers as well

**Comment by fu-raz** [comment]
Just a small update, there's a new v1.0.0 and I suggest everyone to download that version

**Comment by rdfriese** [comment]
Thanks!
