### ISSUE TITLE
Riing Trio and Duo Missing

### ISSUE THREAD

**Issue by ButtonBright0907** [fu-raz/FanControlThermaltake#5]
Hey thanks for making this.

I have a 3 Riing Duos and 3 Riing Trios which of these controllers and nothing showed up in FanControl using default plugin. 

I altered the product id to x2135 and then 4 of the 6 fans showed up with some usability. 

Product Id 8503 and 9003 where shown in the test program.

https://github.com/MoshiMoshi0/ttrgbplusapi/blob/master/controllers/riing-trio.md is for the trio.

Any help you could give would be appreciated.

**Comment by fu-raz** [comment]
I'm working on refactoring the plugin so we can add more controllers. I'll see if I can add some of the other controllers found in the TTRGBPlusAPI

**Comment by fu-raz** [comment]
Could you try the latest version? https://github.com/fu-raz/FanControlThermaltake/releases/tag/v0.0.3

**Comment by ButtonBright0907** [comment]
Thanks for working on this. 

I tried the latest version and it is still not seeing the other controller. 

I used SignalRGB and found the PID is 0x232b which doesn't align with moshi's information.

**Comment by ButtonBright0907** [comment]
Turns out, they aren't the trio's they are the new "swafans"
The rgb is controlled the same way as trios.

**Comment by fu-raz** [comment]
Hmmm, this will make it a little harder for me to test. I could try to add your PID in a test version if you'd like? Can't promise it'll work though

**Comment by fu-raz** [comment]
https://github.com/fu-raz/FanControlThermaltake/releases/tag/v0.0.5-BETA Could you give this a try?

**Comment by ButtonBright0907** [comment]
Thanks for working on this. 
I was able to see all of the SWAFANs. However, another issue has arisen with the trios. Now only fans 2and 3 are showing and a fake fan4 has shown up. Fan1 does not respond to fan4 inputs. 
When moved to fan 4 spot, fan4 disappears and a fake fan5 appears. If moved to the fan5 spot, a fake fan1 appears in fancontrol and changing settings does not affect the fan.

**Comment by fu-raz** [comment]
I've been seeing somewhat the same behavior with my fans. I've been trying to work out what's going on. I'll release a new version if when get it fixed.

Maybe we should create another issue for this new issue btw

**Comment by fu-raz** [comment]
Everything should be fixed in the latest release! v1.0.0
