### ISSUE TITLE
Need Help wit the Thermaltake Plugin 

### ISSUE THREAD

**Issue by vans936** [fu-raz/FanControlThermaltake#6]
Hi hopefully you can saw this comment, i download the latest FanControl software and i would like to know how or where do i install the thermaltake plugin after dowloading the code. There are no instruction so in my common sense when i dowloaded i extracted and copied your code folder named "FanControlThermaltake-main"  into the FanControl plugin folder. 
But when i open the FanControl in the sensor seting it said "No plugin loaded"so it can't find the plugin i extract.
I probably installed it incorrectly, so to repeat my question  I would like to know how to install the Thermaltake pluging in the FanControl software.

![2023-02-16 (2)](https://user-images.githubusercontent.com/64385560/219464138-429435b8-a3b9-4dd0-aace-c486f98367b3.png)
![2023-02-16 (3)](https://user-images.githubusercontent.com/64385560/219464143-99b8eb29-ac0c-4a0c-8f54-a13c05995fa9.png)
![2023-02-16](https://user-images.githubusercontent.com/64385560/219464145-8ad06178-3adf-4b1c-99fc-78f35a551bca.png)

Last thing: I also tried your (TTest) and its said 
"Found Thermaltake device with Vendor ID 9802 and Product ID 9003
We found an unsupported TT device with product ID 9003
We found 1 Thermaltake devices, 0 supported and 1 unsupported
Please raise an issue here with the unsupported product ID's: https://github.com/fu-raz/FanControlThermaltake/issues
Press any key to exit..."

I have 3 Thermaltake SWAFAN140 (CL-F138-PL14SW-A) it came with their controller it was release in 2022.

Hopefully you can answere somehow Thanks.

**Comment by fu-raz** [comment]
I've added support for the SWAFAN in the latest releases :)
